GET http://localhost:3000/api/

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "third@gmail.com",
    "password": "test1234",
    "firstName": "Third",
    "lastName": "Thirdson",
    "username": "thirduser"
}

### 

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "third@gmail.com",
    "password": "test1234"
}

###

GET http://localhost:3000/api/auth/refresh-token
refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNiMTQ5OTY0LWZlMjctNGMyNi05ODc4LTFkZTczNGFlMGFiMyIsImlhdCI6MTcyNjI5OTcwMiwiZXhwIjoxNzI2OTA0NTAyfQ.GfHdSIUBnQeixApsfHgijJvRLcKfxdGgqhazSaus9PE

###

GET http://localhost:3000/api/reviews?firstResult=11&maxResults=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFkMzRkNGE3LWYwYTUtNDJlMi04ZDU1LWQ0MmVhYTllMjMxMyIsImlhdCI6MTcyNTk1MDIzOCwiZXhwIjoxNzI1OTY0NjM4fQ.tJcR_Tb6-CChQ5UFqUmgwJ4Q98ej7hj3duyrPlk5BIo

###

POST http://localhost:3000/api/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUxODMyN2M1LTBhOGEtNGZmOC1iZGQxLTdjYzc3MmRjMWY5ZiIsImlhdCI6MTcyNjA0NDM0MSwiZXhwIjoxNzI2MDU4NzQxfQ.aDfEk6MpKT2p5waxhEdVhQiUlz4WZSrMK9eH-e-aKAw
Content-Type: application/json
 
{
  "title": "Good Will Hunting",
  "year": 1997,
  "genres": "drama",
  "rating": 8.7,
  "text": "An amazing story about the human character",
  "director": "Gus Van Sant",
  "poster": "https://image.tmdb.org/t/p/w600_and_h900_bestv2/bABCBKYBK7A5G1x0FzoeoNfuj2.jpg"
}

### 

POST http://localhost:3000/api/comments
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNiMTQ5OTY0LWZlMjctNGMyNi05ODc4LTFkZTczNGFlMGFiMyIsImlhdCI6MTcyNjE1ODUwNiwiZXhwIjoxNzI2MTcyOTA2fQ.EoKZQPqFnSpRoohnhxgF6CEE-dPW6eR1DmwlFqUYDeM

{
  "reviewId": 1,
  "text": "Free javascript tutorials at punjabi.com"
}

### 

POST http://localhost:3000/api/reviews/10/add-like-dislike
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJlNmVlMTY4LTc2YWMtNDI1NC04ZGNjLTg1ZDQyZmZmN2MxNyIsImlhdCI6MTcyNjE0OTc3NywiZXhwIjoxNzI2MTY0MTc3fQ.WTMagB5hc7G0J-wtRU81rTltExPoKSLcADCldNrK4yk
Content-Type: application/json


{
  "type": "LIKE"
}

### 

GET http://localhost:3000/api/comments/review/1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNiMTQ5OTY0LWZlMjctNGMyNi05ODc4LTFkZTczNGFlMGFiMyIsImlhdCI6MTcyNjE2MDQ5NSwiZXhwIjoxNzI2MTc0ODk1fQ.SSif5rA4iCG-7-KazvtWAOU9LDd8syvC8jXPYkGNETE