GET http://localhost:3000/api/

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test1234",
    "firstName": "Test",
    "lastName": "User",
    "username": "test001"
}

### 

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test1234"
}

###

GET http://localhost:3000/api/auth/refresh-token
refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFjNTgzMzI5LWI4NGEtNDhiMy1hOGQ1LTY3ZWFhNDE2ZTFiNCIsImlhdCI6MTcyNDc2MzU0MCwiZXhwIjoxNzI1MzY4MzQwfQ.WFknRuC2qtWfCBlO8X0xPvAWTJMg1-E1717A_vK9ZGc

###

GET http://localhost:3000/api/reviews?firstResult=11&maxResults=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFkMzRkNGE3LWYwYTUtNDJlMi04ZDU1LWQ0MmVhYTllMjMxMyIsImlhdCI6MTcyNTk1MDIzOCwiZXhwIjoxNzI1OTY0NjM4fQ.tJcR_Tb6-CChQ5UFqUmgwJ4Q98ej7hj3duyrPlk5BIo

###

POST http://localhost:3000/api/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJlNmVlMTY4LTc2YWMtNDI1NC04ZGNjLTg1ZDQyZmZmN2MxNyIsImlhdCI6MTcyNTk1NjI2MCwiZXhwIjoxNzI1OTcwNjYwfQ.W3wUuY2GSh40aOR-IIFZrge4VEwRgd-6AEZ6qVfQYy4
Content-Type: application/json
 
{
  "title": "Good Will Hunting",
  "year": 1997,
  "genres": "drama",
  "rating": 8.7,
  "text": "An amazing story about the human character",
  "director": "Gus Van Sant",
  "poster": "https://image.tmdb.org/t/p/w600_and_h900_bestv2/bABCBKYBK7A5G1x0FzoeoNfuj2.jpg"
}