GET http://localhost:3000/api/

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test1234",
    "firstName": "Test",
    "lastName": "User",
    "username": "test001"
}

### 

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test1234"
}

###

GET http://localhost:3000/api/auth/refresh-token
refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFjNTgzMzI5LWI4NGEtNDhiMy1hOGQ1LTY3ZWFhNDE2ZTFiNCIsImlhdCI6MTcyNDc2MzU0MCwiZXhwIjoxNzI1MzY4MzQwfQ.WFknRuC2qtWfCBlO8X0xPvAWTJMg1-E1717A_vK9ZGc

###

GET http://localhost:3000/api/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZmMDJkYjZmLWE1OTMtNGEyMy04MDM4LTk2MWE3MDdhNDAzZSIsImlhdCI6MTcyNTU1MTkzNCwiZXhwIjoxNzI1NTY2MzM0fQ.Rrt3Fv6Svqkwe8Jc1-R49FQGvnjI8FIYuslv5CugZvk

###

POST http://localhost:3000/api/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFkMzRkNGE3LWYwYTUtNDJlMi04ZDU1LWQ0MmVhYTllMjMxMyIsImlhdCI6MTcyNTM3MTUzNCwiZXhwIjoxNzI1Mzg1OTM0fQ.VpeDMOUN_tDJ716ikbJVbLfknM2-geHPFPrSnkXxbQ0
Content-Type: application/json
 
{
  "title": "The Godfather",
  "year": 1971,
  "genres": "drama, crime",
  "rating": 10.0,
  "text": "A landmark of cinema",
  "director": "Francis Ford Copolla"
}